name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: sbt clean coverage test
    - name: Test Code with Coverage and Reports
      # You may pin to the exact commit or the version.
      uses: NikoBergemann/action-sbt-test-report@c72cf468ba85251e39d3c64a4f00918d072bb5bc
      # uses: NikoBergemann/action-sbt-test-report@v3
      with:
        # Name of Test Suite(s)
        what-to-test: "*"
    - name: Run Coveralls
      run: sbt coverageReport coveralls
    - name: Dynamic Badges
      uses: Schneegans/dynamic-badges-action@v1.4.0
